# sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node

before_deploy:
  - docker login -u yuanfengli168 -p 19940326daxia

deploy:
  skip_cleanup: true
  # edge: true
  provider: script
  script: docker push mannydesings/node
  on:
    branch: master
